### ISSUE TITLE
Redefine 'Content-type' email header in order to send using HTML snippets

### ISSUE THREAD

**Issue by chrisbalt** [mzur/kirby-contact-form#7]
Currently, if a user (dev) selects a snippet that contains HTML (such as your example [`sendform-table.php` snippet](https://github.com/mzur/kirby-contact-form/blob/master/snippets/sendform-table.php), the HTML will deliver as text and render as such. As far as I can see, the only way to override this is to redefine the `Content-Type` property [currently defined in the email class within the Kirby toolkit](https://github.com/getkirby/toolkit/blob/master/lib/email.php#L137). Alternatively, a duplicate service adopter could be created with this one line changed, but that does not seem desirable.

Is there a way for [`SendForm.php`](https://github.com/mzur/kirby-contact-form/blob/master/sendform/lib/SendForm.php) to force the definition of this header to change?

**Comment by mzur** [comment]
I think there is no way for this plugin to force a change of the header without using a new email service. A simple change of the [default `mail` service](https://github.com/getkirby/toolkit/blob/621b2e078ebda16282e904f56e3c17b853522a5e/lib/email.php#L129-149) would make this possible:

```php
email::$services['html-mail'] = function($email) {
   $headers = array(
      'From: ' . $email->from,
      'Reply-To: ' . $email->replyTo,
      'Return-Path: ' . $email->replyTo,
      'Message-ID: <' . time() . '-' . $email->from . '>',
      'X-Mailer: PHP v' . phpversion(),
      // changed:
      'Content-Type: text/html; charset=utf-8'),
      'Content-Transfer-Encoding: 8bit',
   );
   ini_set('sendmail_from', $email->from);
   $send = mail($email->to, str::utf8($email->subject), str::utf8($email->body), implode(PHP_EOL, $headers));
   ini_restore('sendmail_from');
   if(!$send) {
      throw new Error('The email could not be sent');
   }
};
```

The contact form plugin then would need a new option to set the email service manually.

@chrisbalt would you be happy with this solution? You could make this work right now if you added the above email service and called it `mail`, thus overwriting the default service.

**Comment by chrisbalt** [comment]
@mzur I think you're right, it seems that either modifying the existing service–or adding a new service adopter–with the `Content-Type` properly set is the only way to go. Could instrument a somewhat-elegant solution if a new mail service could be defined outside of the Kirby toolkit. Could then detect some string (like "html") in the snippet filename, which would trigger use of the `html-mail` service. Until then, this works just fine.

Thanks for the response.

**Comment by mzur** [comment]
An option to choose a (custom) email service will be added in v1.3 (#11).

**Comment by creichel** [comment]
:+1: @mzur You should add this to the plugin and/or to the README.md!

**Comment by mzur** [comment]
I think it's rather for the Toolkit to implement this and allow different content types with the `mail` service or provide a new `html-mail` service. Feel free to [request](https://github.com/getkirby/toolkit/issues/new) this feature :wink:
