### ISSUE TITLE
Error in `toolkit/lib/v.php`

### ISSUE THREAD

**Issue by DerZyklop** [mzur/kirby-contact-form#8]
I tried to install the plugin. I used the [basic example](https://github.com/mzur/kirby-contact-form#basic). It gives me the following Error:

    Warning: in_array() expects parameter 2 to be array, null given in /[...]/kirby/toolkit/lib/v.php on line 85

The source of this warning is this part:

    <?php e($form->hasError('name'), ' class="erroneous"')?>

**Comment by mzur** [comment]
Could you please provide the whole template and describe the steps producing this error?
